"""empty message

Revision ID: 35d2aec2e1d9
Revises: aef6aa6d44f9
Create Date: 2025-03-08 13:53:48.808698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d2aec2e1d9'
down_revision: Union[str, None] = 'aef6aa6d44f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_table_users_fkey', 'association_table', type_='foreignkey')
    op.drop_constraint('association_table_items_fkey', 'association_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_table', 'users', ['users'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_table', 'items', ['items'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.create_foreign_key('association_table_items_fkey', 'association_table', 'items', ['items'], ['id'])
    op.create_foreign_key('association_table_users_fkey', 'association_table', 'users', ['users'], ['id'])
    # ### end Alembic commands ###
